'use strict';

// tests for hello
// Generated by serverless-jest-plugin

const mod = require('../../src/handlers/hello');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

const bodyParser = (body) => JSON.parse(body);

describe('hello', () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      console.log(bodyParser(response.body));
      expect(bodyParser(response.body).message).toBe(
        'Go Serverless v1.0! Your function executed successfully!'
      );
    });
  });
});
